--- #YAML:1.0
name:               Geo-Address-Mail-Standardizer-USPS-AMS-Results
version:            0.05
abstract:           results object from the USPS Address Matching System
author:
    - Mike Eldridge <diz@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Geo::Address::Mail::Standardizer:  0.01
    Message::Stack:       0.17
    MooseX::Storage:      0.28
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
